[theme]
base = "dark"
primaryColor = "#38BDF8"
backgroundColor = "#08090A"
secondaryBackgroundColor = "#0D0E10"
textColor = "#EDEEF0"
font = "sans serif"

[server]
headless = true
enableCORS = false
port = 8501
maxUploadSize = 200
runOnSave = false

[browser]
gatherUsageStats = false

[runner]
magicEnabled = false
fastReruns = true
